#!/bin/sh -e
# shellcheck disable=SC1003
# This rc will try to use the CONTENT field and fallback to curling
# LINK. Saves lots of time/bandwidth for articles/blogs where the html
# is expected to be embedded into the CONTENT field.

[ "$CONTENT" ] || [ "$LINK" ] || exit 0

if [ "$CONTENT_TYPE" = html ]; then
	ext=.html
else
	ext=
fi

# Sanitize the filename
filename=$(tr '/' '\\') <<-EOF
	${AUTHOR:+$AUTHOR - }${TITLE:-${TIMESTAMP:-$(date +%c)}}$ext
EOF

mkdir -p "$SAKRAHOME/news/"
if [ "$CONTENT" ]; then
	sed 's/\\n/ /g' > "$SAKRAHOME/news/$filename" <<-EOF
		$CONTENT
	EOF
else
	curl -LSsf${V:+v} -- "$LINK" > "$SAKRAHOME/news/$filename"
fi

