#!/bin/sh -e
# shellcheck disable=SC1003
# This rc will try to use the CONTENT field and fallback to curling
# LINK. Saves lots of time/bandwidth for articles/blogs where the html
# is expected to be embedded into the CONTENT field.

if [ ! "$CONTENT" ] && [ ! "$LINK" ]; then
	exit 0
fi

ext=
[ "$CONTENT_TYPE" = html ] && ext=.html

# Sanitize the filename
filename=$(tr '/' '\\') <<-EOF
	${AUTHOR:+$AUTHOR - }${TITLE:-${TIMESTAMP:-$(date +%c)}}$ext
EOF

mkdir -p "$SAKRAHOME/news/"
if [ "$CONTENT" ]; then
	sed 's/\\n//g' > "$SAKRAHOME/news/$filename" <<-EOF
		$CONTENT
	EOF
else
	curl -LSsf -- "$LINK" > "$SAKRAHOME/news/$filename"
fi

