#!/bin/sh -e
# shellcheck disable=SC1003

if [ ! "$CONTENT" ] && [ ! "$LINK" ]; then
	exit 0
fi

ext=
[ "$CONTENT_TYPE" = html ] && ext=.html

# Sanitize the filename
filename=$(tr '/' '\\') <<-EOF
	${AUTHOR:+$AUTHOR - }${TITLE:-${TIMESTAMP:-$(date +%c)}}$ext
EOF

mkdir -p "$SAKRAHOME/news/"
if [ "$CONTENT" ]; then
	cat > "$SAKRAHOME/news/$filename" <<-EOF
		$CONTENT
	EOF
else
	curl -LSsf -- "$LINK" > "$SAKRAHOME/news/$filename"
fi

