#!/bin/sh -e
# Downloads YouTube links as m3u files into ~/youtube/ so they can be
# streamed by a media player (i.e. mpv w/ youtube-dl)
#
# Also consider checking out this script for converting YouTube links
# into RSS feeds https://github.com/AN3223/scripts/blob/master/y2rss

if ! { [ "$LINK" ] && [ "${FEEDNAME:-$AUTHOR}" ] && [ "$TITLE" ]; }; then
	exit 0
fi

mkdir -p "$SAKRAHOME/youtube"

# Sanitize the filename
filename=$(tr '/' '\\') <<-EOF
	${FEEDNAME:-$AUTHOR} - $TITLE
EOF

printf '%s\n' "$LINK" > "$SAKRAHOME/youtube/$filename.m3u"

