#!/bin/sh -eC
# Downloads YouTube links as m3u files into ~/youtube/ so they can be
# streamed by a media player (e.g., mpv w/ youtube-dl)

if ! { [ "$LINK" ] && [ "${FEEDNAME:-$AUTHOR}" ] && [ "$TITLE" ]; }; then
	exit 0
fi

mkdir -p "$SAKRAHOME/youtube"

# Sanitize the filename
filename=$(tr '/' '\\') <<-EOF
	${FEEDNAME:-$AUTHOR} - $TITLE
EOF

printf '%s\n' "$LINK" > "$SAKRAHOME/youtube/$filename.m3u"

