#!/bin/sh -e
# Downloads YouTube videos with youtube-dl into ~/youtube/
#
# Also consider checking out this script for converting YouTube links
# into RSS feeds https://github.com/AN3223/scripts/blob/master/y2rss

[ "$LINK" ] || exit 0
mkdir -p "$SAKRAHOME/youtube"

youtube-dl ${NV:+--no-progress} ${V:+-q} ${VVV:+-v} \
	--no-mtime --match-filter !is_live --no-overwrites --no-post-overwrites \
	-o "$SAKRAHOME/youtube/${FEEDNAME:-%(uploader)s} - %(title)s.%(ext)s" "$LINK"

