#!/bin/sh -e
# Downloads YouTube videos with youtube-dl into ~/youtube/
#
# Also consider checking out this script for converting YouTube links
# into RSS feeds https://github.com/AN3223/scripts/blob/master/y2rss

[ ! "$LINK" ] && exit 0
mkdir -p "$HOME/youtube"

template='$HOME/youtube/%(uploader)s - %(title)s.%(ext)s'
youtube-dl -q --no-warnings --no-mtime -o "$template" "$LINK"

